name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 2.2.0
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^1.1.2
  http_parser: ^4.0.1
  video_player: ^2.4.2

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.2

flutter:
